sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - rm ~/.m2/settings.xml
script:
  - mvn clean compile package install && mvn javadoc:javadoc
notifications:
  email:
    on_success: never
    on_failure: never
jdk: oraclejdk8
