spring:
  datasource:
    url: jdbc:mysql://localhost:3306/communikey?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: create-drop
cckey:
  security:
    oauth2:
      access_token_validity: 604800
      refresh_token_validity: 604800